app/news/urls.py
from django.urls import path
from django.conf.urls.i18n import i18n_patterns
from app.news.views import NewsView, NewsDetailsView

app_name = 'news'

urlpatterns = (
    path('news/', NewsView.as_view(), name='news'),
    path('news-detail/<int:id>/', NewsDetailsView.as_view(), name='news-detail'),
)

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns



urlpatterns = [
    path("admin/", admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path("", include("app.settings.urls")),
    path("", include("app.news.urls")),
    path("", include("app.destinations.urls")),
    path("", include("app.tour.urls")),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/include/footer.html
{% load static %}

<footer class="site-footer">
    <div class="site-footer__top">
        <div class="container">
            <div class="site-footer__top-inner">
                <div class="row">
                    <div class="col-xl-4 col-lg-6 col-md-6 wow fadeInUp" data-wow-delay="100ms">
                        <div class="footer-widget__column footer-widget__about">
                            <div class="footer-widget__about-logo">
                                <a href="index.html"><img src="{% static 'assets/images/logo.png' %}" alt="" style="height: 110px; width: 150px;"></a>
                            </div>
                            <p class="footer-widget__about-text">Welcome to our Trip and Tour Agency. Lorem
                                simply text amet cing elit.</p>
                        </div>
                    </div>
                    <div class="col-xl-2 col-lg-6 col-md-6 wow fadeInUp" data-wow-delay="200ms">
                        <div class="footer-widget__column footer-widget__company clearfix">
                            <h3 class="footer-widget__title">Company</h3>
                            <ul class="footer-widget__company-list list-unstyled">
                                <li><a href="{% url 'about' %}">О нас</a></li>
                                <li><a href="#">Community Blog</a></li>
                                <li><a href="#">Rewards</a></li>
                                <li><a href="#">Work with Us</a></li>
                                <li><a href="#">Meet the Team</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-2 col-lg-6 col-md-6 wow fadeInUp" data-wow-delay="300ms">
                        <div class="footer-widget__column footer-widget__explore">
                            <h3 class="footer-widget__title">Explore</h3>
                            <ul class="list-unstyled footer-widget__explore-list">
                                <li><a href="#">Account</a></li>
                                <li><a href="#">Legal</a></li>
                                <li><a href="#">Contact</a></li>
                                <li><a href="#">Affilitate Program</a></li>
                                <li><a href="#">Privacy Policy</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-4 col-lg-6 col-md-6 wow fadeInUp" data-wow-delay="400ms">
                        <div class="footer-widget__column footer-widget__newsletter">
                            <h3 class="footer-widget__title">Newsletter</h3>
                            <form class="footer-widget__newsletter-form mc-form"
                                data-url="https://xyz.us18.list-manage.com/subscribe/post?u=20e91746ef818cd941998c598&id=cc0ee8140e">
                                <div class="footer-widget__newsletter-input-box">
                                    <input type="email" placeholder="Email address" name="EMAIL">
                                    <button type="submit" class="footer-widget__newsletter-btn">Subscribe</button>
                                </div>
                            </form>
                            <div class="mc-form__response text-center"></div><!-- /.mc-form__response -->
                            <div class="footer-widget__newsletter-bottom">
                                <div class="footer-widget__newsletter-bottom-icon">
                                    <i class="fa fa-check"></i>
                                </div>
                                <div class="footer-widget__newsletter-bottom-text">
                                    <p>I agree to all terms and policies</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="site-footer__bottom">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="site-footer__bottom-inner">
                        <div class="site-footer__bottom-left">
                            <div class="footer-widget__social">
                                <a href="#"><i class="fab fa-twitter"></i></a>
                                <a href="#"><i class="fab fa-facebook"></i></a>
                                <a href="#"><i class="fab fa-pinterest-p"></i></a>
                                <a href="#"><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                        <div class="site-footer__bottom-right">
                            <p>@ All Copyright 2021, <a href="#">Bracket Web</a></p>
                        </div>
                        <div class="site-footer__bottom-left-arrow">
                            <a href="#" data-target="html" class="scroll-to-target scroll-to-top"><span
                                    class="icon-right-arrow"></span></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

<div class="mobile-nav__wrapper">
    <div class="mobile-nav__overlay mobile-nav__toggler"></div>
    <!-- /.mobile-nav__overlay -->
    <div class="mobile-nav__content">
        <span class="mobile-nav__close mobile-nav__toggler"><i class="fa fa-times"></i></span>

        <div class="logo-box">
            <a href="index.html" aria-label="logo image"><img src="{% static 'assets/images/logo.png' %}" width="155"
                    alt="" /></a>
        </div>
        <!-- /.logo-box -->
        <div class="mobile-nav__container"></div>
        <!-- /.mobile-nav__container -->

        <ul class="mobile-nav__contact list-unstyled">
            <li>
                <i class="fa fa-envelope"></i>
                <a href="mailto:needhelp@packageName__.com">needhelp@tevily.com</a>
            </li>
            <li>
                <i class="fa fa-phone-alt"></i>
                <a href="tel:666-888-0000">666 888 0000</a>
            </li>
        </ul><!-- /.mobile-nav__contact -->
        <div class="mobile-nav__top">
            <div class="mobile-nav__social">
                <a href="#" class="fab fa-twitter"></a>
                <a href="#" class="fab fa-facebook-square"></a>
                <a href="#" class="fab fa-pinterest-p"></a>
                <a href="#" class="fab fa-instagram"></a>
            </div><!-- /.mobile-nav__social -->
        </div><!-- /.mobile-nav__top -->



    </div>
    <!-- /.mobile-nav__content -->
</div>
<!-- /.mobile-nav__wrapper -->

<div class="search-popup">
    <div class="search-popup__overlay search-toggler"></div>
    <!-- /.search-popup__overlay -->
    <div class="search-popup__content">
        <form action="#">
            <label for="search" class="sr-only">search here</label><!-- /.sr-only -->
            <input type="text" id="search" placeholder="Search Here..." />
            <button type="submit" aria-label="search submit" class="thm-btn">
                <i class="icon-magnifying-glass"></i>
            </button>
        </form>
    </div>
    <!-- /.search-popup__content -->
</div>

templates/include/header.html
{% load static %}

<header class="main-header clearfix">
    <nav class="main-menu clearfix">
        <div class="main-menu-wrapper clearfix">
            <div class="container clearfix">
                <div class="main-menu-wrapper-inner clearfix">
                    <div class="main-menu-wrapper__left clearfix">
                        <div class="main-menu-wrapper__logo">
                            <a href="{% url 'index' %}">
                                <img src="{% static 'assets/images/logo.png' %}" alt="" style="width: 80px;">
                            </a>
                        </div>
                        <div class="main-menu-wrapper__main-menu">
                            <a href="#" class="mobile-nav__toggler"><i class="fa fa-bars"></i></a>
                            <ul class="main-menu__list">
                                <li class="dropdown current">
                                    <a href="{% url 'index' %}">Главная страница</a>
                                </li>
                                <li class="dropdown">
                                    <a href="{% url 'destinations' %}">Направления</a>
                                </li>
                                <li class="dropdown">
                                    <a href="#">Туры</a>
                                    <ul>
                                        <li><a href="{% url 'tour' %}">Туры</a></li>
                                        <li><a href="tours-list.html">Список туров</a></li>
                                        <li><a href="tour-details.html">Подробности тура</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a href="{% url 'about' %}">О нас</a>
                                </li>
                                <li class="dropdown">
                                    <a href="{% url 'news:news' %}">Новости</a>
                                </li>
                                <li><a href="{% url 'contact' %}">Контакты</a></li>
                                <li aria-checked="true" role="menuitem">
                                    <a class="language-switch" data-language="en">English</a>
                                    <a class="language-switch" data-language="ru">Русский</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="main-menu-wrapper__right">
                        <a href="#" class="main-menu__search search-toggler icon-magnifying-glass"></a>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</header>

<div class="preloader">
    <img class="preloader__image" width="60" src="{% static 'assets/images/logo.png' %}" alt=""
        style="width: 200px; height: 190px;" />
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const languageSwitches = document.querySelectorAll('.language-switch');

        const currentLanguage = window.location.pathname.split('/')[1];

        languageSwitches.forEach(function (languageSwitch) {
            const selectedLanguage = languageSwitch.getAttribute('data-language');

            if (selectedLanguage === currentLanguage) {
                languageSwitch.classList.add('active-language');
            }

            languageSwitch.addEventListener('click', function () {
                const pathSegments = window.location.pathname.split('/');
                if (['ru', 'en'].includes(pathSegments[1])) {
                    pathSegments[1] = selectedLanguage;
                } else {
                    pathSegments.splice(1, 0, selectedLanguage);
                }

                const newPath = pathSegments.join('/');
                const newUrl = window.location.origin + newPath + window.location.search;

                window.location.href = newUrl;
            });
        });
    });
</script>

templates/include/homepage.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Ecoland</title>
    <!-- favicons Icons -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'assets/images/logo.png' %}" />
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/images/logo.png' %}" />
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/images/logo.png' %}" />
    <link rel="manifest" href="{% static 'assets/images/logo.png' %}" />
    <meta name="description" content="Tevily HTML Template For Tour" />

    <!-- fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400;1,500;1,700&display=swap"
        rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'assets/vendors/bootstrap/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/animate/animate.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/animate/custom-animate.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/fontawesome/css/all.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/jarallax/jarallax.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/jquery-magnific-popup/jquery.magnific-popup.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/nouislider/nouislider.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/nouislider/nouislider.pips.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/odometer/odometer.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/swiper/swiper.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/tevily-icons/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/tiny-slider/tiny-slider.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/reey-font/stylesheet.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/owl-carousel/owl.carousel.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/owl-carousel/owl.theme.default.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/twentytwenty/twentytwenty.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/bxslider/jquery.bxslider.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/bootstrap-select/css/bootstrap-select.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/vegas/vegas.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/jquery-ui/jquery-ui.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/timepicker/timePicker.css' %}" />

    <!-- template styles -->
    <link rel="stylesheet" href="{% static 'assets/css/tevily.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/tevily-responsive.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>

    {%block content%}

    {%endblock%}


    <!-- /.search-popup -->
    <script src="{% static 'assets/vendors/jquery/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'assets/vendors/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendors/jarallax/jarallax.min.js' %}"></script>
    <script src="{% static 'assets/vendors/jquery-ajaxchimp/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'assets/vendors/jquery-appear/jquery.appear.min.js' %}"></script>
    <script src="{% static 'assets/vendors/jquery-circle-progress/jquery.circle-progress.min.js' %}"></script>
    <script src="{% static 'assets/vendors/jquery-magnific-popup/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'assets/vendors/jquery-validate/jquery.validate.min.js' %}"></script>
    <script src="{% static 'assets/vendors/nouislider/nouislider.min.js' %}"></script>
    <script src="{% static 'assets/vendors/odometer/odometer.min.js' %}"></script>
    <script src="{% static 'assets/vendors/swiper/swiper.min.js' %}"></script>
    <script src="{% static 'assets/vendors/tiny-slider/tiny-slider.min.js' %}"></script>
    <script src="{% static 'assets/vendors/wnumb/wNumb.min.js' %}"></script>
    <script src="{% static 'assets/vendors/wow/wow.js' %}"></script>
    <script src="{% static 'assets/vendors/isotope/isotope.js' %}"></script>
    <script src="{% static 'assets/vendors/countdown/countdown.min.js' %}"></script>
    <script src="{% static 'assets/vendors/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/vendors/twentytwenty/twentytwenty.js' %}"></script>
    <script src="{% static 'assets/vendors/twentytwenty/jquery.event.move.js' %}"></script>
    <script src="{% static 'assets/vendors/bxslider/jquery.bxslider.min.js' %}"></script>
    <script src="{% static 'assets/vendors/bootstrap-select/js/bootstrap-select.min.js' %}"></script>
    <script src="{% static 'assets/vendors/vegas/vegas.min.js' %}"></script>
    <script src="{% static 'assets/vendors/jquery-ui/jquery-ui.js' %}"></script>
    <script src="{% static 'assets/vendors/timepicker/timePicker.js' %}"></script>
    <!-- template js -->
    <script src="{% static 'assets/js/tevily.js' %}"></script>
</body>

</html>